In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.preprocessing import LabelEncoder


df = pd.read_csv("https://raw.githubusercontent.com/mujahidashraf/data/ab06025689b4d8904b6a3e330dc8012cf4316f92/data.csv")
le = LabelEncoder()
#df['Car'] = le.fit_transform(df['Car'])
#df['Model'] = le.fit_transform(df['Model'])
df.head()

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [ ]:
X = df[['Car'	,'Model',	'Volume',	'Weight']]
X = pd.get_dummies(X, columns=['Car'	,'Model'])
X.head()

Volume  Weight  Car_Audi  Car_BMW  Car_Fiat  Car_Ford  Car_Honda  \
0    1000     790     False    False     False     False      False   
1    1200    1160     False    False     False     False      False   
2    1000     929     False    False     False     False      False   
3     900     865     False    False      True     False      False   
4    1500    1140     False    False     False     False      False   

   Car_Hundai  Car_Hyundai  Car_Mazda  ...  Model_Octavia  Model_Rapid  \
0       False        False      False  ...          False        False   
1       False        False      False  ...          False        False   
2       False        False      False  ...          False        False   
3       False        False      False  ...          False        False   
4       False        False      False  ...          False        False   

   Model_S60  Model_SLK  Model_Space Star  Model_Swift  Model_Up!  Model_V70  \
0      False      False             False        False      False      False   
1      False      False              True        False      False      False   
2      False      False             False        False      False      False   
3      False      False             False        False      False      False   
4      False      False             False        False      False      False   

   Model_XC70  Model_Zafira  
0       False         False  
1       False         False  
2       False         False  
3       False         False  
4       False         False  

[5 rows x 54 columns]

In [ ]:
y = df['CO2']
y.head()

0     99
1     95
2     95
3     90
4    105
Name: CO2, dtype: int64

In [ ]:
regr = LinearRegression()
regr.fit(X, y)

predictedCO2 = regr.predict(X)

print(predictedCO2)


[ 99.  95.  95.  90. 105. 105.  90.  92.  98.  99.  99. 101.  99.  94.
  97.  97.  99. 104. 104. 105.  94.  99.  99.  99.  99. 102. 104. 114.
 109. 114. 115. 117. 104. 108. 109. 120.]


In [ ]:
regr.intercept_

81.00997208854953

In [ ]:
regr.coef_

array([-2.00000000e-03,  1.88919054e-02,  6.76729148e-01,  1.02804639e+00,
       -2.77573514e+00, -1.79848379e+00, -3.73131883e+00, -2.93031934e+00,
        8.37980302e-01,  1.60419449e+00,  1.07048001e+00,  2.72662787e+00,
       -2.76229119e+00, -1.56922963e+00, -2.24273598e+00,  1.94352077e+00,
        2.53271132e+00,  4.21972389e+00,  1.17009969e+00, -5.62546938e+00,
        2.90223299e+00,  1.60419449e+00,  3.75128278e+00, -2.77573514e+00,
       -1.28679030e+01, -1.21239247e+00, -1.83564031e+00,  3.72476192e+00,
       -4.36697666e+00,  2.53271132e+00,  4.65700851e+00, -4.66790300e+00,
       -4.75709354e+00,  6.82183763e-01, -3.73131883e+00,  2.72662787e+00,
        6.79803970e+00, -6.91835921e+00,  7.80712876e-01,  4.70006131e+00,
        8.37980302e-01, -2.93031934e+00, -3.41838339e+00, -1.19362665e+01,
       -3.29928227e+00,  7.29272173e+00, -5.91211794e+00,  1.65653398e+01,
       -2.76229119e+00,  1.94352077e+00,  4.21972389e+00,  1.24755627e+00,
        5.83466136e+00,  

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error,r2_score
mae = mean_absolute_error(y , predictedCO2)
mse = mean_squared_error(y , predictedCO2)
rmse = np.sqrt(mse)
r2=r2_score(y , predictedCO2)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")
print(100*'_')




MAE: 1.3816108750890836e-13
MSE: 3.181809105360767e-26
RMSE: 1.7837626258448088e-13
R2: 1.0
____________________________________________________________________________________________________


In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/mujahidashraf/data/ab06025689b4d8904b6a3e330dc8012cf4316f92/data.csv")
le = LabelEncoder()
df['Car'] = le.fit_transform(df['Car'])
df['Model'] = le.fit_transform(df['Model'])
df.head()

Car  Model  Volume  Weight  CO2
0   14     10    1000     790   99
1   10     29    1200    1160   95
2   12     14    1000     929   95
3    2      4     900     865   90
4    9     16    1500    1140  105

In [ ]:
X = df[['Car'	,'Model',	'Volume',	'Weight']]
X.head()

Car  Model  Volume  Weight
0   14     10    1000     790
1   10     29    1200    1160
2   12     14    1000     929
3    2      4     900     865
4    9     16    1500    1140

In [ ]:
y = df['CO2']
y.head()

0     99
1     95
2     95
3     90
4    105
Name: CO2, dtype: int64

In [ ]:
regr = LinearRegression()
regr.fit(X, y)

predictedCO2 = regr.predict(X)

print(predictedCO2)

[ 92.27318912  99.50662857  93.91127198  91.39998351  99.85593289
  96.42710067  99.04474779  99.77174878 100.2881439   99.46569382
  96.32298253  99.20523175  96.2062409  101.44158484 103.00054537
 100.87131703 100.02023971 104.46250106 101.9709201  106.03036887
 105.16317038 106.96208289 105.74070471 103.88362042 107.34254847
 101.69323023 105.25687952 107.04979412 105.59547642 106.1173318
 108.18032487 110.5701707  100.73926175 100.34765688 105.21853873
 111.66283494]


In [ ]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error,r2_score
mae = mean_absolute_error(y , predictedCO2)
mse = mean_squared_error(y , predictedCO2)
rmse = np.sqrt(mse)
r2=r2_score(y , predictedCO2)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")
print(100*'_')

MAE: 4.758472757674434
MSE: 31.632498138456747
RMSE: 5.624277565915177
R2: 0.4145058114591762
____________________________________________________________________________________________________


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, random_state=10)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()


In [ ]:
logr=LogisticRegression(solver='liblinear')
logr.fit(X_train,y_train)


LogisticRegression(solver='liblinear')

In [ ]:
predl=logr.predict(X_test)

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

74.65436175904686

In [ ]:
model.coef_

array([0.11650695, 0.03557492, 0.01025034, 0.00704761])

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([107.95203427, 110.49824175,  93.34805824,  93.76708242,
       100.75978148,  94.30235273, 100.49954106,  90.35115899])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2=r2_score(y_test , y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")
print(100*'_')
mae = mean_absolute_error(y_test , predl)
mse = mean_squared_error(y_test , predl)
rmse = np.sqrt(mse)
r2=r2_score(y_test , predl)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")

MAE: 5.705962317776956
MSE: 44.50925876067645
RMSE: 6.671525969422322
R2: 0.3163924740380867
____________________________________________________________________________________________________
MAE: 7.125
MSE: 80.125
RMSE: 8.951256894984079
R2: -0.23062155027597786
