In [ ]:
import numpy as np

# Sigmoid and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Dummy training data (X: 2 features, Y: 2 outputs)
# You can replace this with your actual data
mydata_X = np.array([[0.05, .1]])

mydata_Y = np.array([[0.01, .99]])

# Seed for reproducibility
np.random.seed(42)




In [ ]:
# Initialize weights and biases
input_neurons = 2
hidden_neurons = 2
output_neurons = 2



In [ ]:
# Weights
#W1 = np.random.rand(input_neurons, hidden_neurons)
#W2 = np.random.rand(hidden_neurons, output_neurons)

W1 = np.array([[0.15, .2],
               [.25,.30]])
W2 = np.array([[0.40, .45],
               [.50,.55]])

# Biases
b1 = np.array([[.35,.35]])
b2 = np.array([[.60,.60]])


In [ ]:
b2

array([[0.6, 0.6]])

In [ ]:

# Training the neural network
epochs = 20000
learning_rate = 0.6

for epoch in range(epochs):
    # Forward pass
    z1 = np.dot(mydata_X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Compute error
    error = mydata_Y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(mydata_X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update weights and biases
    W2 += learning_rate * d_W2
    b2 += learning_rate * d_b2
    W1 += learning_rate * d_W1
    b1 += learning_rate * d_b1

    # print("\nFinal Weights and Biases after Training:")
    # print("W1 (Input to Hidden):")
    # print(W1)
    # print("\nb1 (Hidden Layer Biases):")
    # print(b1)
    # print("\nW2 (Hidden to Output):")
    # print(W2)
    # print("\nb2 (Output Layer Biases):")
    # print(b2)
    #break
    # Optionally print loss
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch} Loss: {loss:.6f}")



# Test the model
print("\nFinal output after training:")
output = sigmoid(np.dot(sigmoid(np.dot(mydata_X, W1) + b1), W2) + b2)
print(output)

Streaming output truncated to the last 5000 lines.
b2 (Output Layer Biases):
[[-2.41729919  2.24021263]]

Final Weights and Biases after Training:
W1 (Input to Hidden):
[[0.18377637 0.23224733]
 [0.31755274 0.36449465]]

b1 (Hidden Layer Biases):
[[1.0255274 0.9949465]]

W2 (Hidden to Output):
[[-1.5058423   1.524989  ]
 [-1.39607706  1.61803597]]

b2 (Output Layer Biases):
[[-2.41730073  2.2402141 ]]

Final Weights and Biases after Training:
W1 (Input to Hidden):
[[0.18377641 0.23224737]
 [0.31755283 0.36449474]]

b1 (Hidden Layer Biases):
[[1.02552827 0.99494737]]

W2 (Hidden to Output):
[[-1.50584345  1.52499009]
 [-1.3960782   1.61803705]]

b2 (Output Layer Biases):
[[-2.41730227  2.24021556]]

Final Weights and Biases after Training:
W1 (Input to Hidden):
[[0.18377646 0.23224741]
 [0.31755291 0.36449482]]

b1 (Hidden Layer Biases):
[[1.02552914 0.99494824]]

W2 (Hidden to Output):
[[-1.50584459  1.52499117]
 [-1.39607934  1.61803813]]

b2 (Output Layer Biases):
[[-2.41730382  2.24

In [ ]:
print("\nFinal Weights and Biases after Training:")
print("W1 (Input to Hidden):")
print(W1)
print("\nb1 (Hidden Layer Biases):")
print(b1)
print("\nW2 (Hidden to Output):")
print(W2)
print("\nb2 (Output Layer Biases):")
print(b2)


Final Weights and Biases after Training:
W1 (Input to Hidden):
[[0.18379041 0.23226142]
 [0.31758082 0.36452284]]

b1 (Hidden Layer Biases):
[[1.0258082  0.99522842]]

W2 (Hidden to Output):
[[-1.50621396  1.52534105]
 [-1.39644648  1.61838589]]

b2 (Output Layer Biases):
[[-2.41780031  2.24068731]]


In [ ]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load Iris dataset
iris = load_iris()
mydata_X = np.array([[0.05, .1]])

mydata_Y = np.array([[0.01, .99]])
X = mydata_X  # Features
y = mydata_Y

model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=(X.shape[1],)),  # Input layer
    tf.keras.layers.Dense(2, activation='sigmoid'),  # Hidden layer with 10 neurons and ReLU activation
    tf.keras.layers.Dense(2, activation='sigmoid')  # Output layer with 3 neurons (for 3 classes) and softmax activation
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X, y, epochs=1, verbose=2)

test_loss, test_acc = model.evaluate(X, y)
print(f"Test Accuracy: {test_acc:.4f}")

# Make predictions
predictions = model.predict(X)
print(predictions)#


1/1 - 1s - 578ms/step - accuracy: 1.0000 - loss: 0.5562
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 1.0000 - loss: 0.5541
Test Accuracy: 1.0000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[0.4326399  0.50916404]]


In [ ]:
# Get weights and biases from the model
for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()
    print(f"\nLayer {i + 1}:")
    print(f"Weights:\n{weights}")
    print(f"Biases:\n{biases}")



Layer 1:
Weights:
[[0.49134302 1.1084404 ]
 [0.82672036 0.5851033 ]]
Biases:
[-0.00099997  0.00099998]

Layer 2:
Weights:
[[ 0.05737705 -1.0510302 ]
 [-0.5679942   1.1141721 ]]
Biases:
[-0.00099999  0.00099999]


In [ ]:
import numpy as np

# Model's predicted output
predicted = np.array([[0.08397181, 0.7599313]])

# Real expected output
expected = np.array([[0.01, 0.99]])

# Apply threshold of 0.5 to get binary output
binary_output = (predicted >= 0.5).astype(int)

# Print results
print("Predicted Raw Output:", predicted)
print("Binary Output (Threshold 0.5):", binary_output)
print("Expected Output:", expected)


Predicted Raw Output: [[0.08397181 0.7599313 ]]
Binary Output (Threshold 0.5): [[0 1]]
Expected Output: [[0.01 0.99]]
