In [ ]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels


encoder = OneHotEncoder(sparse_output=False)
y_onehot = encoder.fit_transform(y.reshape(-1, 1))


X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=(X_train.shape[1],)),  # Input layer
    tf.keras.layers.Dense(10, activation='relu'),  # Hidden layer with 10 neurons and ReLU activation
    tf.keras.layers.Dense(3, activation='softmax')  # Output layer with 3 neurons (for 3 classes) and softmax activation
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=150, batch_size=8, validation_split=0.2, verbose=0)

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")

# Make predictions
predictions = model.predict(X_test)
print(predictions)#
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)
true_classes = np.argmax(y_test, axis=1)

print(f"Predictions: {predicted_classes}")
print(f"True labels: {true_classes}")


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 429ms/step - accuracy: 1.0000 - loss: 0.0736
Test Accuracy: 1.0000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
[[1.9727398e-03 9.3154365e-01 6.6483609e-02]
 [9.9504191e-01 4.9570370e-03 9.0457900e-07]
 [6.5993738e-08 7.3128514e-04 9.9926853e-01]
 [3.2599734e-03 8.3208638e-01 1.6465363e-01]
 [1.9444653e-03 8.5775352e-01 1.4030203e-01]
 [9.9106783e-01 8.9293169e-03 2.8585039e-06]
 [2.7896749e-02 9.6254712e-01 9.5562134e-03]
 [9.5321579e-05 2.9196337e-02 9.7070831e-01]
 [2.5908963e-04 5.4410243e-01 4.5563850e-01]
 [6.2110196e-03 9.7280604e-01 2.0982938e-02]
 [5.4931059e-04 1.3708198e-01 8.6236870e-01]
 [9.9627936e-01 3.7196227e-03 1.0964999e-06]
 [9.9580544e-01 4.1937488e-03 7.8863303e-07]
 [9.9627423e-01 3.7246919e-03 1.0899022e-06]
 [9.9801922e-01 1.9805136e-03 1.7011827e-07]
 [7.7616130e-03 8.0530250e-01 1.8693575e-01]
 [7.8233434e-06 9.0155909e-03 9.9097663e-01]
 [3.7899308e-03 9.7434616e-01 2.1863962e-02]
 [3.2490771e-03 9.4392943e-01 5.2821495e-02]
 [5.2581149

In [ ]:
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
