In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder ,MinMaxScaler,StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV
from sklearn.model_selection import train_test_split, cross_val_score,GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score,recall_score,precision_score
import seaborn as sns
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.svm import l1_min_c
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/mujahidashraf/data/refs/heads/main/Titanic-Dataset.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
imputer = SimpleImputer(strategy='mean')  # You can also use 'median' or 'most_frequent'
df[['Age']] = imputer.fit_transform(df[['Age']])
imputer1 = SimpleImputer(strategy='most_frequent')  # You can also use 'median' or 'most_frequent'
df[['Embarked']] = imputer1.fit_transform(df[['Embarked']])
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
'''
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = 1
df['IsAlone'].loc[df['FamilySize'] > 1] = 0
df['Title'] = df['Name'].apply(lambda x: x.split(',')[1].split('.')[0].strip())
df['AgeBin'] = pd.cut(df['Age'], bins=[0, 12, 18, 30, 50, 80], labels=["Child", "Teenager", "YoungAdult", "Adult", "Senior"])
df['FareBin'] = pd.qcut(df['Fare'], 4, labels=["Low", "Medium", "High", "VeryHigh"])'''

'\ndf[\'FamilySize\'] = df[\'SibSp\'] + df[\'Parch\'] + 1\ndf[\'IsAlone\'] = 1\ndf[\'IsAlone\'].loc[df[\'FamilySize\'] > 1] = 0\ndf[\'Title\'] = df[\'Name\'].apply(lambda x: x.split(\',\')[1].split(\'.\')[0].strip())\ndf[\'AgeBin\'] = pd.cut(df[\'Age\'], bins=[0, 12, 18, 30, 50, 80], labels=["Child", "Teenager", "YoungAdult", "Adult", "Senior"])\ndf[\'FareBin\'] = pd.qcut(df[\'Fare\'], 4, labels=["Low", "Medium", "High", "VeryHigh"])'

In [ ]:
df=df.drop(columns=['PassengerId',	'Name','Cabin',		'Ticket'])
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])
df['Pclass'] = le.fit_transform(df['Pclass'])
#df['Title'] = le.fit_transform(df['Title'])
#df['AgeBin'] = le.fit_transform(df['AgeBin'])
#df['FareBin'] = le.fit_transform(df['FareBin'])
#df = pd.get_dummies(df, columns=['Sex', 'Embarked','Pclass','Title','AgeBin','FareBin'])
#print(len(df))
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       2    1  22.0      1      0   7.2500         2
1         1       0    0  38.0      1      0  71.2833         0
2         1       2    0  26.0      0      0   7.9250         2
3         1       0    0  35.0      1      0  53.1000         2
4         0       2    1  35.0      0      0   8.0500         2

In [ ]:
X=df.drop(columns=['Survived'])
y=df['Survived']
scaler = StandardScaler()
X = scaler.fit_transform(X)

#min_c = l1_min_c( X=X, y=y)
#print(f"Minimum useful C for L1 regularization: {min_c:.5f}")

Minimum useful C for L1 regularization: 0.00106


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 10)

In [ ]:
svm = LinearSVC()
svm.fit(X_train, y_train)

LinearSVC()

In [ ]:
y_predict=svm.predict(X_test)
accuracy = accuracy_score(y_test, y_predict)
print("Test Accuracy:", accuracy)
print(classification_report(y_test, y_predict))

Test Accuracy: 0.8097014925373134
              precision    recall  f1-score   support

           0       0.84      0.87      0.86       174
           1       0.74      0.70      0.72        94

    accuracy                           0.81       268
   macro avg       0.79      0.78      0.79       268
weighted avg       0.81      0.81      0.81       268



In [ ]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1','l2'],  # 'l1' requires 'liblinear' solver, which LinearSVC doesn't use
    'dual': [True, False],
    'max_iter': [1000, 5000],
    'multi_class': ['ovr', 'crammer_singer']

}

# Grid search with cross-validation
grid = GridSearchCV(LinearSVC(), param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid.fit(X_train, y_train)

# Best parameters and model
print("Best Parameters:", grid.best_params_)

# Evaluate on test set
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_pred))

Best Parameters: {'C': 100, 'dual': True, 'loss': 'hinge', 'max_iter': 1000, 'multi_class': 'ovr', 'penalty': 'l2'}
Test Accuracy: 0.8208955223880597

Classification Report on Test Set:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       174
           1       0.79      0.67      0.72        94

    accuracy                           0.82       268
   macro avg       0.81      0.79      0.80       268
weighted avg       0.82      0.82      0.82       268



In [ ]:
model = NuSVC()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8097014925373134

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86       174
           1       0.75      0.68      0.72        94

    accuracy                           0.81       268
   macro avg       0.79      0.78      0.79       268
weighted avg       0.81      0.81      0.81       268



In [ ]:
param_grid = {
    'nu': [0.1, 0.3, 0.5, 0.7],      # Nu (controls margin)
    'kernel': ['rbf', 'poly', 'sigmoid'],   # Kernel type
    'gamma': ['scale', 'auto', 0.1, 1]  # Kernel coefficient for rbf, poly, sigmoid
}

nu_svc = NuSVC()

grid_search = GridSearchCV(nu_svc, param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Best parameters and best score from grid search
print("Best Parameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_

# Predict and evaluate on the test set
y_pred = best_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_pred))
#for get duumies
#Best Parameters: {'gamma': 'scale', 'kernel': 'rbf', 'nu': 0.5}
#Accuracy: 0.8395522388059702

Best Parameters: {'gamma': 'auto', 'kernel': 'rbf', 'nu': 0.5}
Accuracy: 0.8097014925373134

Classification Report on Test Set:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       174
           1       0.75      0.68      0.72        94

    accuracy                           0.81       268
   macro avg       0.79      0.78      0.79       268
weighted avg       0.81      0.81      0.81       268



In [ ]:
svc11 = SVC()
svc11.fit(X_train, y_train)

# Predict and evaluate on the test set
y_pred = svc11.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report on Test Set:")
print(classification_report(y_test, y_pred))

Accuracy: 0.832089552238806
Classification Report on Test Set:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87       174
           1       0.77      0.74      0.76        94

    accuracy                           0.83       268
   macro avg       0.82      0.81      0.81       268
weighted avg       0.83      0.83      0.83       268



In [ ]:
svc11.n_support_

array([155, 147], dtype=int32)

In [ ]:
svc11.support_vectors_

array([[ 0.82737724,  0.73769513, -2.13156761, ...,  0.76762988,
        -0.22408312,  0.58595414],
       [-1.56610693,  0.73769513,  1.17746947, ..., -0.47367361,
         0.06635974,  0.58595414],
       [ 0.82737724, -1.35557354, -2.05461326, ...,  0.76762988,
        -0.22408312,  0.58595414],
       ...,
       [ 0.82737724, -1.35557354, -0.20770885, ...,  2.00893337,
        -0.42425614,  0.58595414],
       [ 0.82737724, -1.35557354, -1.0542067 , ..., -0.47367361,
        -0.49271408, -0.67817453],
       [ 0.82737724,  0.73769513, -1.36202411, ..., -0.47367361,
        -0.42207354, -1.9423032 ]])

In [ ]:
param_grid = {
    'C': [0.1, 1, 10],               # Regularization parameter
    'kernel': ['rbf', 'poly', 'sigmoid', 'linear'],  # Type of kernel
    'gamma': ['scale', 'auto', 0.1, 1],  # Kernel coefficient for rbf, poly, sigmoid
    'degree': [3, 4, 5]              # Only for 'poly' kernel, degree of the polynomial
}

svc = SVC()
grid_search = GridSearchCV(svc, param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)
print("Best Parameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_

# Predict and evaluate on the test set
y_pred = best_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_pred))

Best Parameters: {'C': 1, 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf'}
Accuracy: 0.832089552238806

Classification Report on Test Set:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87       174
           1       0.77      0.74      0.76        94

    accuracy                           0.83       268
   macro avg       0.82      0.81      0.81       268
weighted avg       0.83      0.83      0.83       268



In [ ]:
cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[153  21]
 [ 24  70]]


In [ ]:
svc=SVC()
parameters = [ {'C':[1, 10, 100, 1000], 'kernel':['linear']},
               {'C':[1, 10, 100, 1000], 'kernel':['rbf'], 'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]},
               {'C':[1, 10, 100, 1000], 'kernel':['poly'], 'degree': [2,3,4] ,'gamma':[0.01,0.02,0.03,0.04,0.05]}
              ]

grid_search = GridSearchCV(estimator = svc,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 3,
                           verbose=0)


grid_search.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'degree': [2, 3, 4],
                          'gamma': [0.01, 0.02, 0.03, 0.04, 0.05],
                          'kernel': ['poly']}],
             scoring='accuracy')

In [ ]:
print('GridSearch CV best score : {:.4f}\n\n'.format(grid_search.best_score_))
print('Parameters that give the best results :','\n\n', (grid_search.best_params_))
print('\n\nEstimator that was chosen by the search :','\n\n', (grid_search.best_estimator_))
print('GridSearch CV score on test set: {0:0.4f}'.format(grid_search.score(X_test, y_test)))

GridSearch CV best score : 0.8139


Parameters that give the best results : 

 {'C': 1, 'gamma': 0.2, 'kernel': 'rbf'}


Estimator that was chosen by the search : 

 SVC(C=1, gamma=0.2)
GridSearch CV score on test set: 0.8209


In [ ]:
best_model = grid_search.best_estimator_

# Predict and evaluate on the test set
y_pred = best_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Accuracy: 0.8208955223880597
Confusion matrix

 [[155  19]
 [ 29  65]]
